version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cinehex-rabbit
    ports:
      - "5672:5672"   # Puerto de mensajería (AMQP)
      - "15672:15672" # Interfaz Web de gestión
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest